id: A77B9728C
base_file: f83DE.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:07:25.328539
  last_modified_at: 2022-05-30 23:07:25.328545
