id: A77B9728C
base_file: f3662.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:07:25.319066
  last_modified_at: 2022-05-30 23:07:25.319070
