id: A77B9728C
base_file: fD32F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:07:25.330348
  last_modified_at: 2022-05-30 23:07:25.330351
