id: A77B9728C
base_file: f510F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:07:25.324943
  last_modified_at: 2022-05-30 23:07:25.324951
